<?

set_time_limit (60);
$errorReporting = (E_ALL & ~E_NOTICE);
$errorReporting = 1; 	// comment this out to enable PHP warnings
error_reporting($errorReporting);

if (is_readable("config/media_dispatcher.php")) {
    include("config/media_dispatcher.php");
} else {
    print "Please copy config/media_dispatcher.php.sample to config/media_dispatcher.php and set up your own dispatcher\n";
    exit;
}

require("library/media_sessions.php");

$filters=array('user'=>$_REQUEST['user']);

$MediaSessions = new MediaSessions($dispatcher,$filters);
$MediaSessions->show();

?>
