<?

set_time_limit (60);
$errorReporting = (E_ALL & ~E_NOTICE);
$errorReporting = 1; 	// comment this out to enable PHP warnings
error_reporting($errorReporting);

$sample_config = "config/media_sessions.conf.sample";
$local_config  = "config/media_sessions.conf";
$system_config = "/etc/mediaproxy/web/media_sessions.conf";

if (is_readable($local_config)) {
    include($local_config);
    $file_name = $local_config;
} elseif (is_readable($system_config)) {
    include($system_config);
    $file_name = $system_config;
} else {
    print "Please copy $sample_config to $local_config and set the address of the MediaProxy dispatcher\n";
    exit;
}

if ($dispatcher == "undefined") {
    print "Please edit $file_name and set the address of the Mediaproxy dispatcher\n";
    exit;
}

require("library/media_sessions.php");

$filters=array('user'=>$_REQUEST['user']);

$MediaSessions = new MediaSessions($dispatcher,$filters);
$MediaSessions->show();

?>
